import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Dialogs
import "../components"

Item {
    id: root
    property string extractedText: ""
    property string activeApiUsed: ""
    property string copyFeedback: ""

    Connections {
        target: quickConvertController
        function onConversion_completed(content, apiLabel) {
            root.extractedText = content;
            root.activeApiUsed = apiLabel;
        }
    }

    FileDialog {
        id: imagePicker
        title: "Select Image for OCR Extraction"
        nameFilters: ["Image Files (*.png *.jpg *.jpeg *.webp)", "All Files (*)"]
        onAccepted: {
            quickConvertController.convert_image(selectedFile.toString(), promptField.text);
        }
    }

    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 20
        spacing: 16

        Text {
            text: "Quick Convert (Single-Image OCR)"
            color: "#F9FAFB"
            font.pixelSize: 20
            font.bold: true
        }

        Card {
            Layout.fillWidth: true
            Layout.preferredHeight: 140

            DropArea {
                anchors.fill: parent
                onDropped: function(drop) {
                    if (drop.hasUrls && drop.urls.length > 0) {
                        quickConvertController.convert_image(drop.urls[0].toString(), promptField.text);
                    }
                }

                ColumnLayout {
                    anchors.centerIn: parent
                    spacing: 10

                    Text {
                        text: "Drag and drop an image (PNG, JPG, WebP) or click below"
                        color: "#9CA3AF"
                        font.pixelSize: 14
                        Layout.alignment: Qt.AlignHCenter
                    }

                    TextField {
                        id: promptField
                        Layout.preferredWidth: 400
                        placeholderText: "Optional custom prompt instructions (e.g. Extract formula to LaTeX)"
                        Layout.alignment: Qt.AlignHCenter
                    }

                    Button {
                        id: selectImgBtn
                        objectName: "selectImageFileButton"
                        text: "Select Image File"
                        highlighted: true
                        Layout.alignment: Qt.AlignHCenter
                        enabled: typeof quickConvertController !== "undefined" && quickConvertController ? !quickConvertController.isBusy : true
                        onClicked: imagePicker.open()
                    }
                }
            }
        }

        RowLayout {
            Layout.fillWidth: true
            spacing: 16
            visible: typeof quickConvertController !== "undefined" && quickConvertController ? quickConvertController.isBusy : false

            BusyIndicator {
                running: true
                Layout.preferredWidth: 28
                Layout.preferredHeight: 28
            }

            Text {
                text: "Converting image via AI vision model... Please wait."
                color: "#60A5FA"
                font.pixelSize: 14
            }
        }

        RowLayout {
            Layout.fillWidth: true
            spacing: 16

            Text {
                text: "Extracted Markdown Output"
                color: "#E5E7EB"
                font.pixelSize: 16
                font.bold: true
            }

            Text {
                text: root.activeApiUsed ? ("Generated by: " + root.activeApiUsed) : ""
                color: "#34D399"
                font.pixelSize: 12
            }

            Item { Layout.fillWidth: true }

            Text {
                text: root.copyFeedback
                color: "#10B981"
                font.pixelSize: 12
            }

            Button {
                text: "Copy Markdown"
                enabled: root.extractedText.length > 0
                onClicked: {
                    quickConvertController.copy_to_clipboard(root.extractedText);
                    root.copyFeedback = "Copied to clipboard!";
                }
            }

            Button {
                text: "Clear"
                enabled: root.extractedText.length > 0
                onClicked: {
                    root.extractedText = "";
                    root.activeApiUsed = "";
                    root.copyFeedback = "";
                }
            }
        }

        ScrollView {
            Layout.fillWidth: true
            Layout.fillHeight: true
            clip: true

            TextArea {
                id: resultArea
                width: parent.width
                text: root.extractedText
                readOnly: true
                wrapMode: TextArea.Wrap
                color: "#F3F4F6"
                font.family: "Monospace"
                background: Rectangle {
                    color: "#111827"
                    border.color: "#374151"
                    radius: 6
                }
            }
        }
    }
}
