import QtQuick
import QtQuick.Controls
import QtQuick.Dialogs
import "../components"

Item {
    id: root
    property string extractedText: ""
    property string activeApiUsed: ""
    property string copyFeedback: ""

    Connections {
        target: quickConvertController
        function onConversion_completed(content, apiLabel) {
            root.extractedText = content;
            root.activeApiUsed = apiLabel;
        }
    }

    FileDialog {
        id: imagePicker
        title: "Select Image for OCR Extraction"
        nameFilters: ["Image Files (*.png *.jpg *.jpeg *.webp)", "All Files (*)"]
        onAccepted: {
            quickConvertController.convert_image(selectedFile.toString(), promptField.text);
        }
    }

    Column {
        anchors.fill: parent
        anchors.margins: 20
        spacing: 16

        Text {
            text: "Quick Convert (Single-Image OCR)"
            color: "#F9FAFB"
            font.pixelSize: 20
            font.bold: true
        }

        Card {
            width: parent.width
            height: 140

            DropArea {
                anchors.fill: parent
                onDropped: function(drop) {
                    if (drop.hasUrls && drop.urls.length > 0) {
                        quickConvertController.convert_image(drop.urls[0].toString(), promptField.text);
                    }
                }

                Column {
                    anchors.centerIn: parent
                    spacing: 10

                    Text {
                        text: "Drag and drop an image (PNG, JPG, WebP) or click below"
                        color: "#9CA3AF"
                        font.pixelSize: 14
                        anchors.horizontalCenter: parent.horizontalCenter
                    }

                    TextField {
                        id: promptField
                        width: 400
                        placeholderText: "Optional custom prompt instructions (e.g. Extract formula to LaTeX)"
                        anchors.horizontalCenter: parent.horizontalCenter
                    }

                    Button {
                        text: "Select Image File"
                        highlighted: true
                        anchors.horizontalCenter: parent.horizontalCenter
                        enabled: typeof quickConvertController !== "undefined" && quickConvertController ? !quickConvertController.isBusy : true
                        onClicked: imagePicker.open()
                    }
                }
            }
        }

        Row {
            width: parent.width
            spacing: 16
            visible: typeof quickConvertController !== "undefined" && quickConvertController ? quickConvertController.isBusy : false

            BusyIndicator {
                running: true
                width: 28
                height: 28
            }

            Text {
                text: "Converting image via AI vision model... Please wait."
                color: "#60A5FA"
                font.pixelSize: 14
                anchors.verticalCenter: parent.verticalCenter
            }
        }

        Row {
            width: parent.width
            spacing: 16

            Text {
                text: "Extracted Markdown Output"
                color: "#E5E7EB"
                font.pixelSize: 16
                font.bold: true
                anchors.verticalCenter: parent.verticalCenter
            }

            Text {
                text: root.activeApiUsed ? ("Generated by: " + root.activeApiUsed) : ""
                color: "#34D399"
                font.pixelSize: 12
                anchors.verticalCenter: parent.verticalCenter
            }

            Item { width: 1; height: 1; anchors.fill: parent }

            Text {
                text: root.copyFeedback
                color: "#10B981"
                font.pixelSize: 12
                anchors.verticalCenter: parent.verticalCenter
            }

            Button {
                text: "Copy Markdown"
                enabled: root.extractedText.length > 0
                onClicked: {
                    quickConvertController.copy_to_clipboard(root.extractedText);
                    root.copyFeedback = "Copied to clipboard!";
                }
            }

            Button {
                text: "Clear"
                enabled: root.extractedText.length > 0
                onClicked: {
                    root.extractedText = "";
                    root.activeApiUsed = "";
                    root.copyFeedback = "";
                }
            }
        }

        ScrollView {
            width: parent.width
            height: parent.height - 270
            clip: true

            TextArea {
                id: resultArea
                width: parent.width
                text: root.extractedText
                readOnly: true
                wrapMode: TextArea.Wrap
                color: "#F3F4F6"
                font.family: "Monospace"
                background: Rectangle {
                    color: "#111827"
                    border.color: "#374151"
                    radius: 6
                }
            }
        }
    }
}
